CREATE TABLE IF NOT EXISTS `azjobs` (
  `OXID` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `AZDATE` date NOT NULL,
  `AZPROJECTID` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `AZMAID` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `AZTIMEREAL` double NOT NULL,
  `AZTIMEBILL` double NOT NULL,
  `AZREMARK` text NOT NULL,
  `AZREMARKINTERNAL` text NOT NULL,
  `AZBILLED` enum('0','1') NOT NULL DEFAULT '0',
  `AZTIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AZBILLABLE` enum('0','1') NOT NULL DEFAULT '1',
  `AZOFFER` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`OXID`),
  KEY `AZPROJECTID` (`AZPROJECTID`),
  KEY `AZMAID` (`AZMAID`),
  KEY `AZDATE` (`AZDATE`),
  KEY `AZBILLED` (`AZBILLED`),
  KEY `AZBILLABLE` (`AZBILLABLE`),
  KEY `AZOFFER` (`AZOFFER`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `azprojects` (
  `OXID` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `AZTITLE` varchar(150) NOT NULL,
  `AZPRICEPERHOUR` double NOT NULL,
  PRIMARY KEY (`OXID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;